[tool.poetry]
name = "plex-manager"
version = "0.1.0"
description = ""
authors = ["Jason Rhubottom <jason@rhusoft.com>"]

[tool.poetry.dependencies]
python = "3.8.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
